module.exports = {
  UPDATE_USER: "UPDATE_USER",
  LINK_ACCOUNT: "LINK_ACCOUNT",
  UNLINK_ACCOUNT: "UNLINK_ACCOUNT",
  CLICK_UNLINK: "CLICK_UNLINK",
  REMOVE_PIN: "REMOVE_PIN",
  CLICK_REMOVE_PIN: "CLICK_REMOVE_PIN",
  ADD_PIN: "ADD_PIN"
};
