module.exports = {
  UPDATE_USER: "UPDATE_USER",
  LINK_ACCOUNT: "LINK_ACCOUNT",
  UNLINK_ACCOUNT: "UNLINK_ACCOUNT",
  CLICK_UNLINK: "CLICK_UNLINK",
  REMOVE_PIN: "REMOVE_PIN",
  CLICK_REMOVE_PIN: "CLICK_REMOVE_PIN",
  ADD_PIN: "ADD_PIN",
  INCR_PAGE: "INCR_PAGE",
  LIKE_PIN: "LIKE_PIN",
  UNLIKE_PIN: "UNLIKE_PIN",
  UPDATE_PINWALL: "UPDATE_PINWALL"
};
